-- Migration 001: delivery fee, cierre de caja manual, categorías de menú
-- Idempotente: se puede ejecutar más de una vez sin romper datos existentes.
-- Obligatoria en prod (ddl-auto: validate). En dev, ejecutar si ddl-auto falló o la BD es antigua.
--
-- Uso local:
--   docker exec -i pizzeria_db psql -U postgres -d pizzeria_db < backend/migrations/001_delivery_fee_manual_cash_menu_categories.sql
--
-- Uso prod:
--   psql "$SPRING_DATASOURCE_URL" -f backend/migrations/001_delivery_fee_manual_cash_menu_categories.sql

-- businesses.delivery_fee (NOT NULL, default 0 para filas existentes)
ALTER TABLE businesses ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10, 2);
UPDATE businesses SET delivery_fee = 0 WHERE delivery_fee IS NULL;
ALTER TABLE businesses ALTER COLUMN delivery_fee SET DEFAULT 0;
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'businesses'
      AND column_name = 'delivery_fee'
      AND is_nullable = 'YES'
  ) THEN
    ALTER TABLE businesses ALTER COLUMN delivery_fee SET NOT NULL;
  END IF;
END $$;

-- orders.delivery_fee (nullable; solo aplica cuando delivery_method = DELIVERY)
ALTER TABLE orders ADD COLUMN IF NOT EXISTS delivery_fee NUMERIC(10, 2);

-- cash_shifts: resumen manual al cerrar caja
ALTER TABLE cash_shifts ADD COLUMN IF NOT EXISTS manual_total_collected NUMERIC(10, 2);
ALTER TABLE cash_shifts ADD COLUMN IF NOT EXISTS manual_category_sales TEXT;

-- menu_categories: categorías configurables por negocio
CREATE TABLE IF NOT EXISTS menu_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    code VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    system_default BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_menu_categories_business_code UNIQUE (business_id, code)
);
