-- Migration 004: pagos divididos por pedido (bares / split payment)
-- Idempotente. Ejecutar en prod antes de desplegar backend con OrderPayment.

CREATE TABLE IF NOT EXISTS order_payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    payment_method VARCHAR(255) NOT NULL,
    amount NUMERIC(10, 2) NOT NULL,
    CONSTRAINT order_payments_method_check CHECK (
        payment_method IN ('CASH', 'CARD', 'TRANSFER')
    )
);

CREATE INDEX IF NOT EXISTS idx_order_payments_order_id ON order_payments(order_id);

-- Backfill: pedidos ya cobrados con un solo medio de pago
INSERT INTO order_payments (order_id, payment_method, amount)
SELECT o.id, o.payment_method, o.total
FROM orders o
WHERE o.payment_status = 'PAID'
  AND o.payment_method IS NOT NULL
  AND o.total IS NOT NULL
  AND NOT EXISTS (
      SELECT 1 FROM order_payments op WHERE op.order_id = o.id
  );
